// MA Added numbering to explicitly tell everyone *not* to change order (as we have state based on that)
// MA You can only append to the end enum
export enum GridBoxType {
    Chart = 1,
    Marketwatch = 2,
    TimeAndSale = 3,
    MarketDepthByOrder = 4,
    MarketDepthByPrice = 5,
    MarketAlerts = 6,
    BigTrades = 7,
    MarketTrades = 8,
    DetailedQuote = 9,
    CompanyNews = 10,
    MarketPreOpen = 11,
    AnalysisCenter = 12,
    DerayahOrders = 13,
    DerayahWallet = 14,
    SnbcapitalOrders = 15,
    SnbcapitalWallet = 16,
    VirtualTradingOrders = 17,
    VirtualTradingPositions = 18,
    TechnicalScope = 19,
    TradesSummary = 20,
    Shareholders = 21,
    ShareholdersList = 22,
    TradestationOrders = 23,
    TradestationPositions = 24,
    TradestationAccountBalance = 25,
    SnbcapitalAccountBalance = 26,
    SnbcapitalOrderSearch = 27,
    MarketMovers = 28,
    RiyadcapitalOrders = 29,
    RiyadcapitalWallet = 30,
    RiyadcapitalAccountBalance = 31,
    RiyadcapitalOrderSearch = 32,
    AlinmainvestOrders = 33,
    AlinmainvestWallet = 34,
    AlinmainvestAccountBalance = 35,
    AlinmainvestOrderSearch = 36,
    AljaziracapitalOrders = 37,
    AljaziracapitalWallet = 38,
    AljaziracapitalAccountBalance = 39,
    AljaziracapitalOrderSearch = 40,
    AlrajhicapitalOrders = 41,
    AlrajhicapitalOrderSearch = 42,
    AlrajhicapitalWallet= 43,
    AlrajhicapitalAccountBalance= 44,
    DerayahBuySell = 45,
    FinancialData = 46,
    CompanyFinancialStatements = 47,
    MusharakaOrders = 48,
    MusharakaWallet = 49,
    MusharakaAccountBalance = 50,
    MusharakaOrderSearch = 51,
    BsfOrders = 52,
    BsfWallet = 53,
    BsfAccountBalance = 54,
    BsfOrderSearch = 55,
    AlkhabeercapitalOrders = 56,
    AlkhabeercapitalWallet = 57,
    AlkhabeercapitalAccountBalance = 58,
    AlkhabeercapitalOrderSearch = 59,
    IndexAnalysis = 60,
}

export class GridBoxUtils {
    public static isTradingBox(type:GridBoxType):boolean {
        return [GridBoxType.DerayahOrders,
            GridBoxType.DerayahWallet,
            GridBoxType.SnbcapitalOrders,
            GridBoxType.SnbcapitalOrderSearch,
            GridBoxType.SnbcapitalWallet,
            GridBoxType.SnbcapitalAccountBalance,
            GridBoxType.RiyadcapitalOrders,
            GridBoxType.RiyadcapitalOrderSearch,
            GridBoxType.RiyadcapitalWallet,
            GridBoxType.RiyadcapitalAccountBalance,
            GridBoxType.AlinmainvestOrders,
            GridBoxType.AlinmainvestOrderSearch,
            GridBoxType.AlinmainvestWallet,
            GridBoxType.AlinmainvestAccountBalance,
            GridBoxType.AljaziracapitalOrders,
            GridBoxType.AljaziracapitalOrderSearch,
            GridBoxType.AljaziracapitalWallet,
            GridBoxType.AljaziracapitalAccountBalance,
            GridBoxType.AlrajhicapitalOrders,
            GridBoxType.AlrajhicapitalOrderSearch,
            GridBoxType.AlrajhicapitalWallet,
            GridBoxType.AlrajhicapitalAccountBalance,
            GridBoxType.VirtualTradingOrders,
            GridBoxType.VirtualTradingPositions,
            GridBoxType.TradestationOrders,
            GridBoxType.TradestationPositions,
            GridBoxType.TradestationAccountBalance
        ].includes(type);
    }
}


