// MA ORing enums, similar to C# example http://stackoverflow.com/questions/1030090/how-do-you-pass-multiple-enum-values-in-c
// MA ORDERING HERE IS IMPORTANT! This is the order in which formatters are applied
export enum SlickGridFormatter {

    None = 1,
    Symbol,
    Direction,
    NumberWhole,
    Number2Digits,
    Number3Digits,
    NumberVariableDigits,
    Percent,
    NegativePositive,
    NegativePositive2Digits,
    NegativePositiveByDirection,
    NegativePositiveByState,
    LiquidityBar,
    DateTime,
    UnixDateTime,
    Market,
    ChangeDigit,

    Circle,
    EyeFilter,

    MarketwatchFlag,
    MarketwatchOpen,
    MarketwatchAlert,
    MarketwatchNewsAnalysis,
    MarketwatchSector,
    MarketwatchTechnicalScope,
    MarketwatchMarketAlerts,
    AnnotationDelayed,
    FlagAnnotation,
    balloonAnnotation,

    MarketPreOpenAnalysis,

    MarketDepthPercentageBar,
    MarketDepthLevelColoring,
    MarketDepthTotalRow,

    CompanyNewsDetails,
    TimeAndSaleState,

    DerayahWalletEdit,
    DerayahWalletCostDiff,
    SnbcapitalWalletEdit,
    SnbcapitalWalletCostDiff,
    RiyadcapitalWalletEdit,
    RiyadcapitalWalletCostDiff,
    AlinmainvestWalletEdit,
    AlinmainvestWalletCostDiff,
    AljaziracapitalWalletEdit,
    AljaziracapitalWalletCostDiff,
    AljaziracapitalCurrentTotalCost,

    DerayahOrderStatus,
    DerayahOrderActions,
    DerayahOrderType,
    DerayahOrderDate,
    DerayahOrderPrice,

    SnbcapitalOrderStatus,
    SnbcapitalOrderActions,
    SnbcapitalOrderType,
    SnbcapitalOrderDate,
    SnbcapitalOrderTime,
    SnbcapitalOrderPrice,

    RiyadcapitalOrderStatus,
    RiyadcapitalOrderActions,
    RiyadcapitalOrderType,
    RiyadcapitalOrderDate,
    RiyadcapitalOrderTime,
    RiyadcapitalOrderPrice,

    AlinmainvestOrderStatus,
    AlinmainvestOrderActions,
    AlinmainvestOrderType,
    AlinmainvestOrderDate,
    AlinmainvestOrderTime,
    AlinmainvestOrderPrice,

    AljaziracapitalOrderStatus,
    AljaziracapitalOrderActions,
    AljaziracapitalOrderType,
    AljaziracapitalOrderDate,
    AljaziracapitalOrderTime,
    AljaziracapitalOrderPrice,

    VirtualTradingPositionsEdit,
    VirtualTradingPositionsCostDiff,
    VirtualTradingOrderStatus,
    VirtualTradingOrderActions,
    VirtualTradingOrderSide,
    VirtualTradingOrderPrice,
    VirtualTradingOrderExecution,
    VirtualTradingOrderExecutionPrice,

    TradestationOrderActions,
    TradestationOrderSide,
    TradestationOrderStatus,
    TradestationExpirationType,
    TradestationRejectedReason,
    TradestationOrderPrice,
    TradestationOrderDate,
    TradestationOrderProfitLoss,
    TradestationOrderQuantity,
    TradestationOrderRouting,

    FinancialDataQuarter,
    FinancialDataDetails,
    FinancialDataNumbers,
    FinancialDataPriceBook,
    FinancialDataFlag,
    FinancialStatementCategory,

    NegativePositive3Digits,

    MusharakaOrderStatus,
    MusharakaOrderActions,
    MusharakaOrderType,
    MusharakaOrderDate,
    MusharakaOrderDateTime,
    MusharakaOrderPrice,
    MusharakaExpirationType,
    BsfOrderStatus,
    BsfOrderActions,
    BsfOrderType,
    BsfOrderDate,
    BsfOrderDateTime,
    BsfOrderPrice,
    BsfExpirationType,
    AlkhabeercapitalOrderStatus,
    AlkhabeercapitalOrderActions,
    AlkhabeercapitalOrderType,
    AlkhabeercapitalOrderDate,
    AlkhabeercapitalOrderDateTime,
    AlkhabeercapitalOrderPrice,
    AlkhabeercapitalExpirationType
}
